'use client';

import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';

const faqs = [
  {
    question: 'What is a plagiarism checker?',
    answer: 'A plagiarism checker is a tool that scans a text to identify instances of plagiarism, which is the act of using someone else\'s work or ideas without proper attribution.',
  },
  {
    question: 'Does this tool detect paraphrased plagiarism?',
    answer: 'Yes, our advanced AI can detect paraphrased content and other forms of subtle plagiarism.',
  },
  {
    question: 'Can it detect AI-generated content?',
    answer: 'Yes, our tool is designed to identify content generated by AI models.',
  },
  {
    question: 'Do you store user text?',
    answer: 'No, we do not store any of the text you submit for analysis. Your privacy is our priority.',
  },
  {
    question: 'Is this tool free to use?',
    answer: 'Yes, our plagiarism checker is free to use.',
  },
  {
    question: 'Can I check academic papers and assignments?',
    answer: 'Absolutely. Our tool is suitable for checking all types of academic work.',
  },
];

const users = [
  'Students',
  'Teachers & Educators',
  'Bloggers & Content Writers',
  'SEO Professionals',
  'Businesses & Agencies',
  'Researchers & Academics',
];

export default function FaqAndUsers() {
  return (
    <div className="grid md:grid-cols-2 gap-12">
      <div>
        <h2 className="text-3xl font-bold mb-8 text-center">Frequently Asked Questions</h2>
        <Accordion type="single" collapsible className="w-full">
          {faqs.map((faq, index) => (
            <AccordionItem key={index} value={`item-${index}`} className="bg-white shadow-md rounded-xl mb-4">
              <AccordionTrigger className="px-6 py-4 text-lg font-semibold">{faq.question}</AccordionTrigger>
              <AccordionContent className="px-6 pb-4 text-gray-600">{faq.answer}</AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
      <div className="text-center">
        <h2 className="text-3xl font-bold mb-8">Who Can Benefit?</h2>
        <ul className="space-y-4">
          {users.map((user, index) => (
            <li key={index} className="bg-white shadow-md rounded-xl px-6 py-4 text-lg font-semibold">{user}</li>
          ))}
        </ul>
      </div>
    </div>
  );
}
